### ISSUE TITLE
We need contributors. Sign up here!

### ISSUE THREAD

**Issue by josteink** [josteink/emacs-oob-reboot#1]
Anyone who says they want to join in, gets access.

Shout out below!

**Comment by ssunday** [comment]
Sure, I'll throw in some suggestions

**Comment by justinjk007** [comment]
But if you are not very good with C can you still sign up?
I have almost 200 commits on my dotemacs Repo thou.. 😂

**Comment by dchrzanowski** [comment]
Sign me up please! I'll do my best, because Emacs deserves it.

**Comment by mguzmann** [comment]
I'll do all I can to help!

**Comment by josteink** [comment]
I've added everyone who has commented or pushed a PR. 

As a collaborator you are free to comment on other issues or merge if there is consensus. 

Please use your powers, as I **dont** want to be a sole authority in this project :)

**Comment by JesusMtnez** [comment]
Sign me up, please! I want to help. 👍

**Comment by jackrusher** [comment]
👋🏻

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
