### ISSUE TITLE
Update overall control of buffers, windows, and frames.

### ISSUE THREAD

**Issue by bretfh** [josteink/emacs-oob-reboot#12]
This is by far my biggest complaint with emacs out of the box. Its these objects of emacs that are the main means of interaction. The chords are rather strenuous for something that is meant to be done often. 

When looking at window managers in linux they have more fluid keybindings to handle windows. Maybe we can take inspiration from them. Perhaps offer something better.

Suggestions?

**Comment by angrybacon** [comment]
- Buffers: what do you mean by "control of buffers"? 
- Windows: see #15.
- Frames: other popular editors, for the majority, don't have the ability to run as a server to welcome clients. I think clicking on the frame to focus it is a pretty sane default actually.

**Comment by bretfh** [comment]
Control of buffers as in all keybindings associated with influencing buffers. Viewing them, deleting them, saving them mainly. 

Should frames even be a thing? Probably due for another thread on a redefining of terms or removal of terms if we begin talking about frames. So ill stop here.

**Comment by angrybacon** [comment]
Provided the tutorial take the changes from this repository as well as legacy default into account and cover basic buffer manipulations, I don't think new users might need anything more than what `ibuffer` provides already. See #13.

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
