### ISSUE TITLE
Bind C-x C-b to ibuffer

### ISSUE THREAD

**Issue by phil-s** [josteink/emacs-oob-reboot#13]
`ibuffer` is vastly superior to `list-buffers`, while remaining easy to use if you don't need the advanced features.

**Comment by justinjk007** [comment]
Wow after 3 years, I didn't know there exited something other than list-buffers , this is so much better.

**Comment by angrybacon** [comment]
I just noticed, `ibuffer` doesn't use the header-line to display the column labels. Am I being too picky?

**Comment by mookid** [comment]
I guess this is an issue report for `ibuffer` maintainers.

**Comment by angrybacon** [comment]
Sure, but would you still enable it by default before this is fixed?

**Comment by mookid** [comment]
I think it would still be useful; I did not even realize the header-line modification before seeing your message.

**Comment by justinjk007** [comment]
@mookid  lol yeah me neither.

**Comment by dchrzanowski** [comment]
> I just noticed, ibuffer doesn't use the header-line to display the column labels. Am I being too picky?

^_^ It is kinda weird alright ^_^
Is it a big issue though for it not to be a default setting?

**Comment by angrybacon** [comment]
For the sake consistency I wouldn't make it default. It strikes me as *unfinished* but that's just me and I may be too rigid at times. Your (plural) call.

**Comment by dchrzanowski** [comment]
I personally prefer the ibuffer over the standard buffer list, although I wouldn't use either one. At the end end of the day if I would have to pick one  I would pick the ibuffer.

**Comment by phil-s** [comment]
FWIW the lack of a header line in ibuffer has never even registered for me. When weighed against the tremendous benefits of ibuffer (the filtering and grouping abilities, for instance), I don't feel the header line is too significant.

**Comment by alandmoore** [comment]
ibuffer uses the header line for displaying filter settings.  Not sure if this precludes using it for the column headers (can one have multiple header lines?), but possibly this is the reason behind that decision?

**Comment by angrybacon** [comment]
Good catch. first time I actually use `ibuffer`.

Nope, can't have multi-line mode-line and header-line.

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
