### ISSUE TITLE
Enable winner-mode by default

### ISSUE THREAD

**Issue by phil-s** [josteink/emacs-oob-reboot#14]
`winner-mode` is incredibly helpful -- but only if it's enabled before you need it.

If it's enabled by default, then when users go looking for a way to restore their window configuration after an unexpected change, the solution will actually work for them there and then.

**Comment by josteink** [comment]
Sounds good. Send a PR? :)

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
