### ISSUE TITLE
Enable minibuffer-depth-indicate-mode by default

### ISSUE THREAD

**Issue by phil-s** [josteink/emacs-oob-reboot#16]
Although it only has an effect when `enable-recursive-minibuffers` is enabled (which *shouldn't* be by default), I think `minibuffer-depth-indicate-mode` is too useful not to be on by default if the user elects to enable recursive minibuffers.

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
