### ISSUE TITLE
Better ediff defaults

### ISSUE THREAD

**Issue by phil-s** [josteink/emacs-oob-reboot#17]
;; Default to side-by-side comparisons in ediff.
    (setq ediff-split-window-function 'split-window-horizontally)

Most people have widescreen monitors nowadays, which I think makes side-by-side diffs a pretty sane default. I certainly find it much easier to view them this way.

Personally I also dislike the default use of a separate control frame in ediff, so I'd also be in favour of the following change. I think the `ediff-setup-windows-plain` approach is more reliable in more situations, as it's not difficult to 'lose' the control frame behind the main frame, or for your window manager to maximise the control frame, making it impractical to use. The plain setup can't really be messed up, OTOH.

    (setq ediff-window-setup-function 'ediff-setup-windows-plain)

**Comment by josteink** [comment]
Sounds reasonable. 

Will it impact diffing in magit? Because there you're typically already split horizontally.

**Comment by angrybacon** [comment]
Unfortunately I can't test it further (read "I'm lazy") at home on Windows, but here is what I have in my configuration:

```elisp
(use-package ediff-util
  :ensure nil
  :preface
  (defun me/setup-ediff-map ()
    (ediff-setup-keymap)
    (define-key ediff-mode-map (kbd "<down>") #'ediff-next-difference)
    (define-key ediff-mode-map (kbd "<up>") #'ediff-previous-difference))
  :init (add-hook 'ediff-mode-hook #'me/setup-ediff-map))

(use-package ediff-wind
  :ensure nil
  :config
  (setq-default
   ediff-split-window-function #'split-window-horizontally
   ediff-window-setup-function #'ediff-setup-windows-plain))
```

Worked fine with Magit last time I actually used that snippet (2 years ago or so).

**Comment by phil-s** [comment]
It doesn't cause issues with Magit. I wasn't aware that Magit was overriding the defaults, but I presume it is simply setting the same variable locally.

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
