### ISSUE TITLE
Enable show-paren-mode by default

### ISSUE THREAD

**Issue by phil-s** [josteink/emacs-oob-reboot#18]
;; Highlight the matching parenthesis
    (show-paren-mode 1)

**Comment by josteink** [comment]
You could commit these and send the suggestions as PRs instead, you know :)

**Comment by phil-s** [comment]
I guess. I was presuming that *discussion* of potential settings was of primary import.

**Comment by mookid** [comment]
I guess that this should be the default (it was the default in old emacs versions, if I am not mistaken).

**Comment by justinjk007** [comment]
@mookid  I thought it was too...but evaluating the current init.el shows that it isn't. I will close this and make a PR
