### ISSUE TITLE
Update and Improve the tutorial

### ISSUE THREAD

**Issue by phillord** [josteink/emacs-oob-reboot#2]
The tutorial is currently very old, worries about people not being on a graphical system and spends 200 lines on cursor control.

Something better should be possible!

**Comment by mguzmann** [comment]
The tutorial would also need to reflect whatever changes are made here, obviously.

**Comment by wasamasa** [comment]
For the record, https://github.com/phillord/emacs-tutorial/blob/master/tutorial.org

**Comment by phillord** [comment]
@wasamasa That's my working version. I'm hacking on tutorial.el now. I was debating what to do with the org file; originally I as going to dump it out to something else, but I am thinking to just use org-mode for the tutorial. We shall see.

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
