### ISSUE TITLE
Minimal but necessary rebindings

### ISSUE THREAD

**Issue by PaulStanley** [josteink/emacs-oob-reboot#22]
Obviously this is going to be hugely controversial. But to my mind weird keybindings are off-putting, and feed into the whole "emacs-is-all-about-weird-and-awful-key-sequences" myth.

High on the target list: C-z and C-o, which are bound to rarely needed functions, leaving two *very basic* commands bound to highly obscure, unconventional and unintuitive keys. (C-x C-f has got to be one of the worst pieces of interface design in history. And I lose count of the number of times I've typed C-x f instead and ended up being asked to set something called a fill-column. As if opening a file is a bit less important, and much less important than inserting a blank line. C-x C-f isn't even symmetrical to C-x C-s!)

Critical for any new user: help (which is quite rationally, if unconventially, bound), opening a file (which isn't either), undoing a mistake (which isn't either), saving a file (which is sort-of-rational, albeit weird to modern eyes), and quitting (which isn't). As far as possible those things should be intuitive.

I realise that C-c, C-x, C-f, C-s and C-n are all big trouble ... but couldn't one sacrifice C-z and C-o and C-q? How much are those actually used anyway? And those who do use them could always rebind.

**Comment by dchrzanowski** [comment]
I've talked about the keybindings in #8  this is definitely something that needs to be addressed. I personally think that all of that Ctrl, Meta, whatever key mashing is weird to say the least....
Per my suggestion a user should have a choice of bindings (schemes of bindings) to choose from. Redesigning the core bindings would be a bad idea as that would definitely upset the ppl who are used to the old-school Emacs bindings.

**Comment by angrybacon** [comment]
> but couldn't one sacrifice C-z and C-o and C-q? How much are those actually used anyway?

@PaulStanley A lot! Especially <kbd>C-q</kbd> and <kbd>C-z</kbd>. I believe most people use `windmove` instead of <kbd>C-o</kbd>.

**Comment by PaulStanley** [comment]
Not for any reasonable interpretation of "a lot": see http://ergoemacs.org/emacs/command-frequency.html. Obviously everyone's use varies and no single solution is perfect, for everyone.

**Comment by josteink** [comment]
> Redesigning the core bindings would be a bad idea as that would definitely upset the ppl who are used to the old-school Emacs bindings.

Agreed.

> Per my suggestion a user should have a choice of bindings (schemes of bindings) to choose from.

That would be a good way to do things. Visual Studio, IntelliJ and lots of products asks you upon first launch what kind of bindings you want. This gives us a clear path forward w.r.t key-setting migration.

We just need to be opinionated enough to dare to suggest one option as the "recommended" option, so that new users don't end up being puzzled by such a screen.

Grimscythe1983 contacted core Emacs-developers on this topic, as seen in https://github.com/josteink/emacs-oob-reboot/issues/8.

@Grimscythe1983: Do you have any conversation to show for? Any public mailing-list for other to read? It would definitely by interesting for the rest of us.

**Comment by dchrzanowski** [comment]
@josteink the conversation was not very long, Eli's concern is the fact that this project is at a too early of a stage. Once we gather enough push and contribution I actually think that we could have an impact on Emacs' future.
[GNU mailing list](http://lists.gnu.org/archive/html/emacs-devel/2017-05/msg00157.html)

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
