### ISSUE TITLE
Emoji Polyfill

### ISSUE THREAD

**Issue by leppert** [josteink/emacs-oob-reboot#29]
Depending on how platform and context specific we'd like to get, we may want to add a fix for consistent emoji support on MacOS. Here's a good description of the issue:

http://stackoverflow.com/questions/22652888/display-all-unicode-characters-in-emacs-under-os-x/22656515

And here's how Spacemacs solves it:

https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Bos/osx/config.el#L19-L23

```elisp
(when (fboundp 'set-fontset-font)
  (set-fontset-font "fontset-default"
                    '(#x1F600 . #x1F64F)
                    (font-spec :name "Apple Color Emoji") nil 'prepend))
```

**Comment by phillord** [comment]
Not convinced this is a usability issue so much as a bug. It may be that it has not been fixed for political reasons, or just because no one has done it.

Can you have a look through the Emacs bug tracker (there's a usability issue all by itself) and see if it's been reported? If not, then that's the place to start.

**Comment by leppert** [comment]
Disabled via this commit:

>   commit 9344612d3cd164317170b6189ec43175757e4231
>  Author: YAMAMOTO Mitsuharu <address@hidden>
>  Date:   Tue Apr 12 08:26:51 2016 +0900
>
>      Disable multicolor fonts on OS X since they are not supported on free system

And here's a thread discussing it:
https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-04/msg00952.html

The patch described above doesn't seem to be working on my system at the moment, so I'm going to dig a little deeper.

**Comment by josteink** [comment]
Added explicit code to disable something which works, because that feature is not yet available on Linux. That's *so* FSF :(

That's also how you create forks.

(Signed Linux-user who thinks multicolor fonts are cool)

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
