### ISSUE TITLE
What cursor-type?

### ISSUE THREAD

**Issue by angrybacon** [josteink/emacs-oob-reboot#31]
Apparently we've grown accustomed to the block-cursor, but non-IT people find it confusing. I'm assuming a vertical bar is a more modern standard.

- What's the default on other popular editors?
- Would it be a legitimate change?

**Comment by phil-s** [comment]
I don't know what other editors do, but if the block cursor is kept then the following could also be considered:

    ;; Stop the cursor blinking
    (blink-cursor-mode -1)

    ;; Cursor stretches to the current glyph's width
    (setq x-stretch-cursor t)

**Comment by josteink** [comment]
I've just tested on Windows:

* Visual Studio uses a bar-cursor
* Visual Studio Code uses a bar-cursor

And *Emacs* uses a bar-cursor. Maybe that's a platform specific setting in Emacs core to match the host platform?

**Comment by jackrusher** [comment]
Personally, I prefer:
```
(blink-cursor-mode 0)
(setq default-cursor-type 'bar)
```

**Comment by PaulStanley** [comment]
Both Atom and Sublime use a bar. Vim of course uses a bar in insert mode. Although I prefer the block, I think that's an idiosyncratic choice, and the bar is the natural choice for "editing" buffers. In an ideal world, I suppose, some other buffers (e.g. buffer lists and dired) where the cursor is serving a slightly different function, might conceivably use a block -- or even `hl-line-highlight`.

**Comment by alandmoore** [comment]
@joesteink On Linux it seems to default to a blinking block cursor.  If it is platform-dependent, it would be interesting to know where it gets these defaults and what reasoning went into them.

**Comment by amlamarra** [comment]
I'm still pretty new to Emacs but have made a lot of config changes in my init.el. However, IIRC, on Windows the default was a block. Personally, I prefer the bar, though I see the pros & cons to each. The bar is more new-user friendly and you know exactly where point is & what delete/backspace will do. Plus, that's what most other GUI text editors default to. Though it really doesn't take that long to get used to the block. And block has the advantage of being easier to find. The one thing I dislike about the block is that sometimes I need to move the cursor to see what character is behind it.

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
