### ISSUE TITLE
Contents of menus

### ISSUE THREAD

**Issue by PaulStanley** [josteink/emacs-oob-reboot#33]
In my view, the actual contents (and labelling) of menus could be improved. OOB they need to be as intuitive as possible, especially because it is precisely the less experienced who use them most. (FWIW I tend to use mode-specific menus in modes I don't use a lot or which are especially complex, as a sort of help function.)

#### File
"Visit new file" should just be "new file" -- this whole idea of "visiting" is weird.
"Open file" should have the keybinding (currently C-x C-f)
"Insert file" seems of questionable relevance, but I suppose it could stay.
"Close" should probably be "Close file" (or buffer) and should add keybinding
The various print commands all need wholesale reconsideration, but that's another topic.
I wonder whether the window and frame commands really belong under the "File" menu. Wouldn't it make more sense to have a "View" menu including them, and some of the options that are "view" specific.

#### Edit
Seems basically clean. (Should probably include redo as well as undo, assuming that functionality is made easy.)

Not sure about the "text properties". Does anyone use that?

#### Options
Seems basically OK, though I wonder whether "Customize Emacs" wouldn't more naturally be called "Preferences" or something. Options relating to how the screen looks at the moment might better be in a view menu.

Should include increasing and reducing font-size.

#### Tools
This I think is a menu that often changes with the mode, but it's a hot mess.

My main comment here would be that one should probably **remove** some options which are not much related to editing, are rarely used, and are unlikely to work "out of the box", particularly those for news and mail. I'd prefer it if other options were only shown if the necessary additional programs are present -- for instance spelling, but I can see that might be tough (presumably some sort of attempt to probe for them could be made at startup?). 

"Directory search" I think does something that users wouldn't expect or often want or be able to use. Remove?

#### Help
Is broadly OK, I think. We would need to make sure the tutorial is updated to reflect the OOB defaults, but again that's a different problem. It would be good if there was a specific help command for customization, since that's something people are likely to want to do.

**Comment by phillord** [comment]
"Visit New File" is on my list. I even got that change onto mainline, but then had to take it out again.

A wholesale revamp would be good.

**Comment by jjrh** [comment]
Chiming in - I gotta say a entire revamp of the 'customize', and the menus, etc are very much needed. 

customize is confusing, and not intuitive what so ever. There are either too many options, not enough options, or too many clicks/keypresses to get where you really want and honestly it's pretty ugly. 

The menus lack any sort of useful stuff, compose new mail is a button? I don't have mail setup so why are you showing me this so prominently but lack stuff I might look for such as turning on a mode for the current buffer?

just my two cents.

**Comment by alandmoore** [comment]
I find the "visit" terminology confusing as well, but I understand the need for a different term as `C-x-C-f` behaves differently than conventional new-file/open-file actions in other editors.  Maybe "Open/Create file", since that's effectively what it does (sort of)?

**Comment by phillord** [comment]
@jjrh Suggest we open a different issue on customize. I would agree, it's confusing.

**Comment by rswgnu** [comment]
This issue was largely solved with the extensive menu work we did for InfoDock (which ran atop XEmacs) in the 1990s.  It included both menubars and mode-specific menus for many modes.  The menus were logically laid out, exposed a large amount of functionality to users in a clear manner and provided extensive cross-references to appropriate documentation for more detail.
You can see the InfoDock menu files here together with a link to the full InfoDock distribution:

https://gist.github.com/rswgnu/b714e01d84f715dedc741f695dda4522

I have already assigned my Elisp code to the FSF so the copyright would simply need updating.
A knowledgable person could update them to Emacs 25/26 in a few days and then you would have an incredible starting point that with 1 button press would toggle between the old menus and this new one.

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
