### ISSUE TITLE
Guide-key functionality?

### ISSUE THREAD

**Issue by jackrusher** [josteink/emacs-oob-reboot#37]
I think there's a good chance that new users would strongly benefit from something like [guide-key](https://github.com/kai2nenobu/guide-key). Even after all these years, it would be useful to _me_ to have the completions of all bindings in unfamiliar modes progressively disclosed.

**Comment by justinjk007** [comment]
Reminds me of [which-key](https://github.com/justbur/emacs-which-key) package. But both which-key and guide-key are not in elpa.. soo

**Comment by jackrusher** [comment]
@justinjk007 It looks like `which-key` is a re0write of `guide-key` that's even better for this purpose. If we were to decide that such functionality should be part of emacs, we could talk to the involved parties about getting it into ELPA.

**Comment by alphapapa** [comment]
Yes, having `which-key` be enabled by default would be a *huge* improvement for new users.

**Comment by justinjk007** [comment]
Whom do we approach to get this into elpa? Which-key dev? or Elpa

**Comment by alphapapa** [comment]
AFAIK the author will have to assign copyright to the FSF to put it in ELPA.

@justbur What do you think?  :)

**Comment by phillord** [comment]
I am happy to help with getting a package into ELPA.

Short answer is, ELPA is fairly inclusive and will take any sane package. I'm a which-key junkie, and think it would go in. But, yes, copyright assignment would be necessary. This can be a small task or a long task depending on how many contributors.

Asking the which-key dev is a good start. Offfering to track down contributors is more likely to result in a yes.

**Comment by justinjk007** [comment]
I already started an issue over at which-key asking his help.

**Comment by vindarel** [comment]
The issue: https://github.com/justbur/emacs-which-key/issues/167 it's going well, 4 out of 5 contributors have signed the copyright paper :)

**Comment by justinjk007** [comment]
@vindarel can you ping us when the package is up on elpa, this way we could add it too init.el. Thanks

**Comment by vindarel** [comment]
OK. I'll watch this.

**Comment by vindarel** [comment]
Hello all, which-key is in elpa  ! https://elpa.gnu.org/packages/which-key.html

**Comment by josteink** [comment]
Wow. Nice. Just tried it (and installed from ELPA). Works like a charm!

**Comment by phillord** [comment]
Guess this means, we can close this issue as successful!

Worth putting this on the front page as a good success!

**Comment by justinjk007** [comment]
yaaas

**Comment by vindarel** [comment]
That's great, but it isn't enabled by default yet, is it ?

**Comment by justinjk007** [comment]
@vindarel enabling it by default is out plan. So I guess the developer of the package can make a pull request to emacs-devel to talk about it.

**Comment by vindarel** [comment]
Why is it out of plan ? I see alphapapa mentioning he'd love it and no more mentions about that.

I can understand it's too disruptive. Shall we talk about how we make which-key more easily discoverable ? (menu, tutorial,…)

**Comment by josteink** [comment]
> I can understand it's too disruptive. Shall we talk about how we make which-key more easily discoverable ? 

That's a good idea and IMO a better approach.
