### ISSUE TITLE
nlinum instead of linum

### ISSUE THREAD

**Issue by a13** [josteink/emacs-oob-reboot#44]
Nlinum is on ELPA, why don't use it instead of linum for prog-mode?

**Comment by angrybacon** [comment]
For one, `nlinum` doesn't work 100% of the time. Some lines are not numbered for no apparent reason.

**Edit**: Somewhat relevant https://github.com/hlissner/emacs-nlinum-hl

**Comment by justinjk007** [comment]
Yes, i have noticed this behaviour too. But I still use it thou. But we don't want to add lot of packages like this.

**Comment by angrybacon** [comment]
@justinjk007 Does it happen enough not to consider `nlinum` as a default? If you ask me, once is already too many.

As far as I know, the only real differences (somewhat visible to a new user) are the performance gains and the position of numbers (fringe versus margin).

**Comment by justinjk007** [comment]
Yes but you don't see any real performance gain unless you open files that
are over like 3000 lines or so. But the broken numbering part I see often when refactoring code and adding new lines in between, but it will come back once I reload the file. It doesn't bother me but it might bother new users. I would say stick with linum.

**Comment by a13** [comment]
JFYI: https://lists.gnu.org/archive/html/emacs-devel/2017-06/msg00318.html

**Comment by justinjk007** [comment]
So I think we should drop this debate then, there are movements on making line numbers native.

**Comment by josteink** [comment]
Agreed.

**Comment by josteink** [comment]
Finished this off by removing the existing linum-addition: https://github.com/josteink/emacs-oob-reboot/commit/1edc2e8ab70bbaa4a9964c15f865b1b5d88e255e
