### ISSUE TITLE
So emacs 26 is almost here, when do we push this idea to the emacs devs.

### ISSUE THREAD

**Issue by justinjk007** [josteink/emacs-oob-reboot#45]

**Comment by brotzeit** [comment]
I saw an answer on stackexchange about [adding timestamps to the message buffer ](https://emacs.stackexchange.com/a/33523/11377) today. But I think it needs the option to disable it. What do you think ?

And submitting it before emacs26 release seems to be a good idea.

**Comment by phillord** [comment]
Emacs 26 will be quite a way of yet. There's likely to be at least six months of feature freeze.

In terms of "pushing to Emacs devs", I think, the best way forward is for people to look at simplest, smallest and best evidenced changes, and take those forward to emacs-devel. FWIW, I am working on the tutorial.

**Comment by josteink** [comment]
Sorry for the absence.

I was busy at work getting things done before the vacation, and then I was *on* vacation. Now I'm back though, with some more time to spare.

I think we should follow @phillord's suggestion, and take things one at a time. The smaller the commits, the fewer things there are to disagree about :)

Technically speaking, I think taking these ideas to the Emacs-devs shouldn't be too hard.

I think we can subdivide the tasks between us, and I think whoever made which change is best suited to present their ideas. Does that sound reasonable?


The following is my proposal/suggestion for how to move forwards. If anyone think we should make this a MD-file in the repo, so we can collaborate on it, I'm all for it.

______

If so, there's a few things every contributor needs to do before moving on.

cc: @angrybacon @amlamarra @ssunday @justinjk007 @jackrusher @alandmoore @leppert @mookid 

**Edit:** -1- comment and already need for corrections/improvements.

Moved to separate file: https://github.com/josteink/emacs-oob-reboot/blob/master/Submitting_Changes_Back_Upstream.md

________

Sounds good?

**Comment by phillord** [comment]
For build, I use some variation of 

     make -j 20 -l 20

`20` is a reasonable default. I use `4` on my old netbook and `50` on my modern desktop. It pushes the bootstrap build down to 5 mins.

On testing, it is worth adding automated ERT unit tests as well; not always possible, but useful.

**Comment by justinjk007** [comment]
Awesome, I only have like one reaal commit rest of them are cleaned up merges from other peoples commits or they were not pushed upstream because someone already added them. I will start with the one I introduced which is the `gc threahold`


edit: May be you should add the great explanation about building and testing Emacs into the `contribution.md` file ?

**Comment by josteink** [comment]
Yeah. I moved the instructions (with phil's feedback) to a separate file:

https://github.com/josteink/emacs-oob-reboot/blob/master/Submitting_Changes_Back_Upstream.md

**Comment by justinjk007** [comment]
Ok great.

**Comment by ssunday** [comment]
@justinjk007 @josteink Sorry, I've been swamped lately. I'm trying to get to this as soon as I can.
