### ISSUE TITLE
Submitted patches

### ISSUE THREAD

**Issue by josteink** [josteink/emacs-oob-reboot#46]
This issue is to track patches submitted to emacs-devel, their status, and possible a link to the mailing-list for easier external tracking.

**Comment by ssunday** [comment]
I submitted a patch for disabling mouse wheel progressive speed. I think I did it correctly.

**Comment by josteink** [comment]
I've submitted a patch for nxml-mode defaults.

https://lists.gnu.org/archive/html/emacs-devel/2018-03/msg00540.html

**Comment by josteink** [comment]
And commited: http://git.savannah.gnu.org/cgit/emacs.git/log/lisp/nxml

**Comment by ssunday** [comment]
Here was my patch message...didn't get committed https://lists.gnu.org/archive/html/emacs-devel/2017-08/msg00624.html

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB.

Thanks for the patches everyone who contributed.

Closing issue and repo :)
