### ISSUE TITLE
Consider enabling counsel-M-x (ivy)

### ISSUE THREAD

**Issue by vindarel** [josteink/emacs-oob-reboot#47]
There's a discussion about enabling ivy globally (#20). My proposal (PR attached) is to at least enable `counsel-M-x`, the ivy version of `M-x` (with a fallback to `C-c M-x`). 

But this proposal is a subset of the ivy one, indeed if ivy is enabled globally it does enable this `counsel-M-x`. So let's revive the completion-framework discussion too :)

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
