### ISSUE TITLE
Consider move-text (first, to be added in Elpa)

### ISSUE THREAD

**Issue by vindarel** [josteink/emacs-oob-reboot#49]
move-text is really handy, it allows like in org-mode to move a line or a region with M-up and M-down (which are not bound by default).

I asked here about Elpa: https://github.com/emacsfodder/move-text/issues/12

**Comment by justinjk007** [comment]
I wrote myself some lisp for this couple of years ago.  But this is better you can move region of text too. I would like this feature in emacs as a beginner actually.

**Comment by vindarel** [comment]
Hello there, can someone give better instructions than me to assign copyright in the above move-text issue ? thanks.

**Comment by phillord** [comment]
@vindarel done

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
