### ISSUE TITLE
Improve mode-line?

### ISSUE THREAD

**Issue by alphapapa** [josteink/emacs-oob-reboot#5]
I've been using Emacs for several years now, but I still don't know what every indicator in the default mode-line means.  It could probably use some improvement.  However, I'm guessing that any significant changes might interfere with terminal use.

**Comment by josteink** [comment]
I'd really love something more visually pleasing like powerline over what we have now. Anything with a more modern look anyhow. 

I think all those strange flags should definitely be shifted further right to give presidence to the buffer-name. 

Anyone have a patch/PR?

**Comment by alphapapa** [comment]
> Anyone have a patch/PR?

I guess this should be discussed elsewhere, but...

I think this project may need clearer guidelines on this.  For example, powerline is nice, but if the goal is to collect patches for upstream submission, a change that large is probably not appropriate.  If this project wants to do something different than, in effect, yet-another-emacs-starter-kit, this probably needs to be hashed out.  :)

**Comment by josteink** [comment]
You're right. Maybe UI-changes will quickly turn this into another starter kit, where things can quickly turn subjective, into matters of preference and opinion. 

Maybe we should scope it down to strictly functional aspects, where improvements can be more objectively considered. 

To me that sounds like a good constraint to work with.

**Comment by josteink** [comment]
> I think this project may need clearer guidelines on this

Feel free to outline one in terms of a PR :)

**Comment by angrybacon** [comment]
I was under the impression that all these mode-line packages where just hacks to work around the stiffness of both the mode-line and header-line. Said packages might also slow down Emacs unless their content is kept minimal.

I actually liked the mode-line when I started using Emacs, mostly because it was so simple. One thing though, I could never remember what the indicators after the character set meant. The lack of *modern look* however could be fixed with the theme.

**Comment by pkkm** [comment]
I think one of the biggest improvements would be to use alignment to make it easier to find things in the modeline and make it look less cluttered. Other editors (e.g. Sublime Text, Atom, VS Code) already do this, so it should look familiar to new Emacs users. Example:

![2017-05-06-161443_676x586_scrot_cut](https://cloud.githubusercontent.com/assets/1701492/25773160/0691ceb4-3279-11e7-8f08-0138f4f534ce.png)

This will require much less code than the whole functionality of powerline. Also, some may find powerline too gaudy; I think it's better for the default config to look understated.

Another improvement in user-friendliness would be to replace the cryptic indicators on the left of the default modeline with ones more similar to other editors. For example, spell out the encoding and line endings (e.g. "utf-8-unix") and display ⚫ or + near the buffer name when it has been modified.

EDIT: [Configuration used for the screenshot](https://github.com/pkkm/.emacs.d/blob/ac4da3548ba982c18b427ba16a5863c7eef43b5f/conf/view/modeline/format.el) (loads powerline but uses only the alignment code).

**Comment by mookid** [comment]
Some references to existing code, about better defaults for the modeline:
http://tromey.com/blog/?p=831

**Comment by jackrusher** [comment]
Powerline isn't much code, and the potential for aesthetic improvement using it with some UTF-8 chars (which would also work in a modern terminal) is quite large.

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
