### ISSUE TITLE
Easier configuration and "auto configuration" for packages

### ISSUE THREAD

**Issue by rapha8l** [josteink/emacs-oob-reboot#51]
Hi,

Great idea !
My concern is that configuring Emacs is not much trivial, and customization group is everything but friendly to use (I've been using Emacs for years as basic user, and still struggle)
Also people may be desoriented by the fact that installing packages doesn't bring anything working by default (for the packages I've installed) and need some manual insertions in config file. Auto-adding (maybe not the best idea) of suggesting to add basic configuration by default would be nice.
Hoping it's not too ambitious
Thanks

**Comment by justinjk007** [comment]
Some of the package developers suggests a basic  config for their packages. I don't know how we will go around suggesting configs for ever package.

**Comment by rapha8l** [comment]
Indeed, it should be in the guidelines of package creating for maintainers

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
