### ISSUE TITLE
Remove trailing whitespace (right trim lines) in all lines

### ISSUE THREAD

**Issue by fniessen** [josteink/emacs-oob-reboot#54]
Dear Dan,

This seems better to me:

    ;; Nuke all trailing whitespaces in the buffer.
    (add-hook 'before-save-hook
            #'(lambda ()                  ; Except for ...
                (let ((buffer-undo-list buffer-undo-list)) ; For goto-chg.
                  (unless (or (derived-mode-p 'message-mode)
                                        ; ... where "-- " is the signature
                                        ; separator (for when using emacsclient
                                        ; to compose emails and doing C-x #).
                              (derived-mode-p 'diff-mode))
                                        ; ... where the patch file can't be
                                        ; changed!
                    (delete-trailing-whitespace)))))

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
