### ISSUE TITLE
Key config on first load 

### ISSUE THREAD

**Issue by dchrzanowski** [josteink/emacs-oob-reboot#8]
There's a lot of talk on reddit already about "breaking" things, people's configs suffering, key bindings reconfigured, etc. Therefore, I suggest that on first load emacs should ask the user about key binding preferences :
1. I have my own .el files, ask me where they are Emacs so that you can import them (from GitHub, zip files, etc.) 
2. I want emacs standard keyboard bindings please 
3. I want Cua mode so that Emacs behaves like "popular" editors 
4. I want Vim-like modal editing key bindings (this option will install evil and a few evil extras, hypothetically).
5. Whatever else is out there??? 

Let's not fool ourselves, editor wars are silly and childish. What we want to do is create a more attractive and mature environment and I believe that this will represent a more open approach. This approach will also show,  at the very beginning,  just how flexible Emacs is and that it can be modified to any preferences.

I am of a strong opinion that a lot of folks would simply put Emacs away based on the fact that they felt forced to use Ctrl +... to move around. Well... Let's move on and show that Emacs is much more than that!
Just one of many suggestions to come.

**Comment by josteink** [comment]
This will obviously take more code, but I think some of these are really good ideas. 

Especially the one about choosing key layout upon first launch.  Should we email Emacs-devel and air that idea there separately?

**Comment by dchrzanowski** [comment]
Sounds like a plan I shall do that so!

**Comment by dchrzanowski** [comment]
I was in touch with Eli Zaretskii on emacs-devel, I did put the message forward and I hope that it will be considered in the future, possibly not in the nearest future as I presume that more pressing matters are at priority.

**Comment by dchrzanowski** [comment]
I emailed the Emacs-devel with this idea [GNU Mailing list](http://lists.gnu.org/archive/html/emacs-devel/2017-05/msg00157.html)

It is something that they might consider in the future. We need more push and contribution for this project to be seen as valuable by the Emacs team. For the time being the issue is closed.

**Comment by josteink** [comment]
That's fair enough. Thanks for the link :)

**Comment by dchrzanowski** [comment]
@josteink I hope you don't mind that I used your name a couple of times :)

**Comment by josteink** [comment]
Oh absolutely not.

I don't think it carries any weight anywhere in the Emacs-organization (apart from possibly being the guy that sometimes reports weird cc-mode issues), but I don't have a problem with it either way.

**Comment by dchrzanowski** [comment]
Ah, no need to be so humble! You have made quite a few impressive packages too.

**Comment by jackrusher** [comment]
I would lobby for CUA+. That is, the platform's default key bindings should do something like what a new user would expect, but we should build up more sophisticated features based on those bindings in a spirit similar to what the current keybindings do.

For example, I have arrow keys mapped to normal arrow behavior, but `C-arrow`, `M-arrow` and `C-M-arrow` each do an augmented version of that arrow key's movement, like:

* `<M-up>` => backward-paragraph
* `<M-down>` => forward-paragraph
* `<M-left>` => left-word
* `<M-right>` => right-word
* `<C-M-left>` => backward-sexp
* `<C-M-right>` => forward-sexp
* `<s-up>` => beginning-of-buffer
* `<s-down>` => end-of-buffer)
* `<s-left>` => move-beginning-of-line)
* `<s-right>` => move-end-of-line)

... some of these mirror CUA on OSX, others emacs itself.

**Comment by dchrzanowski** [comment]
I guess i'm going to reopen this as contributions might be coming in, regardless.

**Comment by phillord** [comment]
My own feeling is that having multiple bindings options is not the way to go. The key space is already full, and it is going to result in many, many packages clashing because they are expecting another default. Packages like spacemacs manage to get around this, but only by heavy rebinding of many packages.

Emacs already has a problem with too many options. Decreasing the number of options is an important step. CUA mode is a good start, I think.

**Comment by jackrusher** [comment]
@phillord It's hard to imagine old schoolers willingly giving up their `C-` bindings for the arrow keys, innit? That leaves us with at least two sets. (I agree, though, that built-in offering of vim bindings is probably a bridge too far.)

**Comment by phillord** [comment]
@jackrusher I don't know whether we could get those `C-` bindings released. I think it is worth a try, especially if we start small and work our way up.

**Comment by dchrzanowski** [comment]
I personally think that Emacs should ship with: Emacs-style, CUA  and Vim (evil being built in). Most of good editors offer these options, why shouldn't Emacs?

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
